ci(travis): forces tests to run when `git push -f`

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -19,8 +19,8 @@ before_install:
   # https://github.com/scikit-learn/scikit-learn/issues/10927
   - |
       set -e
-      # fail loudly when force-pushed
-      MODIFIED_FILES=$(git diff --name-only $TRAVIS_COMMIT_RANGE)
+      # fail loudly when force-pushed, that is why there is the `|| 'dummy.js'` part
+      MODIFIED_FILES=$(git diff --name-only $TRAVIS_COMMIT_RANGE || echo 'dummy.js')
       # waiting for native solution https://github.com/travis-ci/travis-ci/issues/6301
       if ! echo ${MODIFIED_FILES} | grep -qvE '^docs/|^\.gitignore|^\.gitattributes|\.md$|^appveyor\.yml$|^icon.png$|^commitlint\.config\.js$'; then
         echo "Only docs were updated, stopping build process."
