chore(e2e): add monorepo e2e tests, improve unit tests (#1388)

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,47 +1,48 @@
 language: node_js
 
-env:
-  - TS_JEST_E2E_WORKDIR=/tmp/ts-jest-e2e-workdir TS_JEST_E2E_OPTIMIZATIONS=1
-
-cache:
-  npm: true
-  directories:
-    - .cache
-    - /tmp/ts-jest-e2e-workdir/__templates__
-
-node_js:
-  - '10'
-
-sudo: false
-
-before_install:
-  # Disabled, randomly works :-/
-  # https://github.com/scikit-learn/scikit-learn/issues/10927
-  # - |
-  #     set -e
-  #     # fail loudly when force-pushed, that is why there is the `|| 'dummy.js'` part
-  #     MODIFIED_FILES=$(git diff --name-only $TRAVIS_COMMIT_RANGE || echo 'dummy.js')
-  #     # waiting for native solution https://github.com/travis-ci/travis-ci/issues/6301
-  #     if ! echo ${MODIFIED_FILES} | grep -qvE '^docs/|^\.gitignore|^\.gitattributes|\.md$|^appveyor\.yml$|^icon\.png$|^commitlint\.config\.js$'; then
-  #       echo "Only docs were updated, stopping build process."
-  #       exit
-  #     fi
-  # ensure we have npm >= 5.8 so that we can use `npm ci` instead of `npm install` (much faster)
-  - dpkg --compare-versions `npm -v` ge 5.8 || npm i -g npm@latest
-  # we report coverages only within node 10, ensure we have the coveralls bin installed
-  - 'if [[ "$(node --version)" == v10.* ]]; then npm install --global coveralls; fi'
-
-script:
-  - npm run clean -- --when-ci-commit-message
-  # only grab coverage data on node 10
-  - |
-    if [[ "$(node --version)" == v10.* ]]; then
-      npm run test -- --runInBand --coverage;
-    else
-      npm run test -- --runInBand;
-    fi
-  - npm run test:monorepo
-
-after_success:
-  # report coverages to coveralls
-  - 'if [[ "$(node --version)" == v10.* && -s coverage/lcov.info ]]; then cat coverage/lcov.info | coveralls; fi'
+jobs:
+  include:
+    - os: windows
+      node_js: 12
+      env: TS_JEST_E2E_WORKDIR=\%APPDATA%\ts-jest-e2e-workdir TS_JEST_E2E_OPTIMIZATIONS=1
+      cache:
+        npm: true
+        directories:
+          - .cache
+          - \%APPDATA%\ts-jest-e2e-workdir\__templates__
+      before_install:
+        - npm i -g yarn
+      script:
+        - npm run clean -- --when-ci-commit-message
+        - npm run test:monorepo
+    - os: linux
+      node_js: 10
+      env: TS_JEST_E2E_WORKDIR=/tmp/ts-jest-e2e-workdir TS_JEST_E2E_OPTIMIZATIONS=1
+      before_install:
+        # Disabled, randomly works :-/
+        # https://github.com/scikit-learn/scikit-learn/issues/10927
+        # - |
+        #     set -e
+        #     # fail loudly when force-pushed, that is why there is the `|| 'dummy.js'` part
+        #     MODIFIED_FILES=$(git diff --name-only $TRAVIS_COMMIT_RANGE || echo 'dummy.js')
+        #     # waiting for native solution https://github.com/travis-ci/travis-ci/issues/6301
+        #     if ! echo ${MODIFIED_FILES} | grep -qvE '^docs/|^\.gitignore|^\.gitattributes|\.md$|^appveyor\.yml$|^icon\.png$|^commitlint\.config\.js$'; then
+        #       echo "Only docs were updated, stopping build process."
+        #       exit
+        #     fi
+        # we report coverages only within node 10, ensure we have the coveralls bin installed
+        - npm i -g coveralls
+      cache:
+        npm: true
+        yarn: true
+        directories:
+          - .cache
+          - /tmp/ts-jest-e2e-workdir/__templates__
+      script:
+        - npm run clean -- --when-ci-commit-message
+        # only grab coverage data on node 10
+        - npm run test -- --runInBand --coverage
+        - npm run test:monorepo
+      after_success:
+        # report coverages to coveralls
+        - if [[ -s coverage/lcov.info ]]; then cat coverage/lcov.info | coveralls; fi
